name: nlp-reer-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6.13
  - pip=21.2.2
  - pip:
    - numpy==1.19.5
    - pandas==1.1.5
    - scikit-learn==0.24.2
    - snorkel==0.9.8
    - nltk==3.6.7
    - stanza==1.3.0
    - flair==0.10
    - dask[complete]==2021.3.0